### ISSUE TITLE
Customization of File Extensions not possible when using Kubernetes Jenkins Plugin

### ISSUE THREAD

**Issue by mrbq** [kiuwan/jenkins-plugin#5]
Hi,

According to the documentation it should be possible to modify the default file extension (see https://www.kiuwan.com/docs/display/K5/Kiuwan+Supported+Technologies ) by changing the values on the file LanguageInfo.properties. But if you execute a Jenkins pipelines in a Jenkins slave defined by a Kubernetes Pod Template then the KLA (and the LanguageInfo.properties) is downloaded on the first (an only) execution of the static code analysis, making impossible to modify the LanguageInfo.properties before executing the analysis.

¿Does this mean that the KLA does not support custom file extensions when using the Kubernetes Jenkins Plugin?

Best regards,

Thank you.

**Comment by jsalado** [comment]
Hello,

As you say the default file extensions for a given application can be changed as described in the documentation.

Now, for your specific situation, since there is a fresh download of the KLA for every analysis, it is not possible to change the LanguageInfo.properties (at least it would be hard to do and doesn't make sense).

To fully support your situation it would be helpful if you can share the Jenkinsfile with the pipeline that downloads and executes the KLA. The solution is to change our Jenkins plugin to support this. Basically instead of downloading the KLA  in the slave every time it would be distributed from the master, so changeing the LanguageInfo properties in the master would work in your situation. I will take a look to the Kubernetes plugin as well to see if we need to consider something else.

In the meantime I can suggest a workaround that means changes in your Jenkinsfile and adding a conf file with the extensions you need to your repository. This file should be called <Kiuwan app name>.extensions.properties. The contents of the file are same as the default LanguageInfo.properties with the appropriate changes in the extensions for your application. Once the KLA is downloaded an installed, and before you run the analysis, copy this file to <KLA home dir>/conf/apps (you have to add this logic to your Jenkins file). This way you can control the extensions recognized by Kiuwan for a specific application in a file that goes with the code of that application.

Please, send the afore mentioned Jenkinsfile (or script you are running in the pipeline) and keep me posted if your try the workaround.

**Comment by mrbq** [comment]
Hi,

I do not have a Jenkinsfile with the pipeline, it is actually a function implemented in a shared library that is called from a pipeline. The agent execution is:

```
def returnCode = sh(script: "sh /tmp/tools/kiuwan/KiuwanLocalAnalyzer/bin/agent.sh -m \"Custom Model\" -s \"${WORKSPACE}\" -n \"TestApp\" -l ${BUILD_NUMBER}  -wr --user ${USERNAME} --pass ${PASSWORD} --analysis-scope \"partialDelivery\"",
    returnStatus: true)

echo 'return code ' + returnCode;

switch(returnCode){
  case 0:
      break
  case 14:
      currentBuild.result = 'UNSTABLE'
      error('Static Analysis Failed')
      break
  case 1:
  case 10:
      currentBuild.result = 'FAILURE'
      error('Static Analysis Failed')
      break
  case 11:
  case 12:
      currentBuild.result = 'NOT_BUILT'
      error('Static Analysis Failed')
      break
  case 13:
      currentBuild.result = 'ABORTED'
      error('Static Analysis Failed')
      break
  default:
      currentBuild.result = 'NOT_BUILT'
      error('Static Analysis Failed')
  }
```

It would be better, of course, if the kiuwan plugin can support this kind of scenarios out of the box but as you say, for now, a workaround is needed. The workaround you propouse could work, I will test it and come back with the output, but for now I have found another. Since It is not correct to have application scoped configuration when it should be a global configuration, it is conceptually better to change the "LanguageInfo.propeties" than to add a ".extensions.properties" file per application, besides, since the kiuwan exectution is the same for all applications I implemented a previous step that downloads the kiuwan local analyzer by executing:

```
/tmp/tools/kiuwan/KiuwanLocalAnalyzer/bin/agent.sh --defer-init 
```
The modified "LanguageInfo.properties" file is loaded using a configmap into the Jenkins slave and then is copied to ${AGENT_HOME}/conf overriding the default configuration. The problem with this approach is that it downloads (appart from the KLA configuration files) a lot of information about the applications that is not required.

Thank you.

Best regards-

**Comment by jsalado** [comment]
Hi there,

yes if your LanguageInfo changes have to be applied to all applications in your organization, obviously the configuration of this with .extension.properties file at the application scope is not the best in your case. I proposed it because my first thought was the this LanguageInfo change was for a specific application only.

I don't quite understand why you run the KLA with the --defer-init. That only downloads from your Kiuwan account applications info and the corresponding models to use with them, to later run analyses offline.

If this previous step is running in your master you just can change the global LanguageInfo.properties file located in <KiuwanLocalAnalyzer>/conf and then proceed to load it to the different slaves.

Did I understand you correctly?

**Comment by mrbq** [comment]
Hi, 
I think you understood the problem partially. The problem is that if you download the Kiuwan Jenkins Plugin the kiuwan tool hasn’t a LanguageInfo.properties.
That file is downloaded when the agent is called the first time but if you use the Kubernetes Jenkins Plugin then the agent is called only one time per container making impossible to override the LanguageInfo.properties (Since it does not exists).
So the —defer-init command download all the KLA metadata (LanguageInfo.propetties included), after that the LanguageInfo.properties is overwritten. Finally, since the agent was downloaded with the —defer-init command, it is possible to execute the analysis.

Best regards

**Comment by kiuwan** [comment]
Hello,

you are right I partially understood because of my lack of knowledge on the Kubernetes plugin. Now I understand a bit more aboout it I see the scenario is different than I thought. SInce you always have a fresh install of the KLA in everypod that runs a build,as you say you don't have the LanguageInfo.properties to everride it before the first run.
Using the --defer-int, although not design for this, is an imaginative way to solve your problem.
We are taking note of this for the next version of our Jenkins plugin to support this type of set up.
Thanks for your feedback. We'll keep you posted.

**Comment by jsalado** [comment]
Hello,

you are right I partially understood because of my lack of knowledge on the Kubernetes plugin. Now I understand a bit more about it I see the scenario is different than I thought. Since you always have a fresh install of the KLA in everypod that runs a build,as you say you don't have the LanguageInfo.properties to override it before the first run.
Using the --defer-int, although not design for this, is an imaginative way to solve your problem.
We are taking note of this for the next version of our Jenkins plugin to support this type of set up.
Thanks for your feedback. We'll keep you posted.
